
name: k6 Scenrio 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  loadtest:
    name: k6 local test run 

    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest


    steps:
     
     - name: Checkout
       uses: actions/checkout@v1
       
     - name: Run k6 local test
       uses: k6io/action@v0.1
       with:
         filename: Scenario1.js
       env:
        HOST: http://185.233.0.230
        PORT: 3000

